##ASSIGNMENT-1: NEAREST NEIGHBOURS

Importing the required Packages for the code:

In [74]:
import numpy as np 
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import math

Loading the Datasets:

In [75]:
iris_data = load_iris()
X1 = iris_data.data
y1 = iris_data.target

X2 = np.genfromtxt("ionosphere.txt", delimiter=',', usecols=np.arange(34))
y2 = np.genfromtxt("ionosphere.txt", delimiter=',', usecols=34, dtype='int')

Splitting Data into Training and Test sets:

In [76]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, random_state=3005)
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, random_state=3005)

Checking our data:

In [77]:
print(X1[:3])
print("=======================")
print(y1[:3])
print("=======================")
print("=======================")
print(X2[:3])
print("=======================")
print(y2[:3])
print("=======================")
print("=======================")

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]
[0 0 0]
[[ 1.       0.       0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708
   1.       0.0376   0.85243 -0.17755  0.59755 -0.44945  0.60536 -0.38223
   0.84356 -0.38542  0.58212 -0.32192  0.56971 -0.29674  0.36946 -0.47357
   0.56811 -0.51171  0.41078 -0.46168  0.21266 -0.3409   0.42267 -0.54487
   0.18641 -0.453  ]
 [ 1.       0.       1.      -0.18829  0.93035 -0.36156 -0.10868 -0.93597
   1.      -0.04549  0.50874 -0.67743  0.34432 -0.69707 -0.51685 -0.97515
   0.05499 -0.62237  0.33109 -1.      -0.13151 -0.453   -0.18056 -0.35734
  -0.20332 -0.26569 -0.20468 -0.18401 -0.1904  -0.11593 -0.16626 -0.06288
  -0.13738 -0.02447]
 [ 1.       0.       1.      -0.03365  1.       0.00485  1.      -0.12062
   0.88965  0.01198  0.73082  0.05346  0.85443  0.00827  0.54591  0.00299
   0.83775 -0.13644  0.75535 -0.0854   0.70887 -0.27502  0.43385 -0.12062
   0.57528 -0.4022   0.58984 -0.22145  0.431   -0.17365  0.60436 -0.2418
   0.

Calculating the Euclidean Distance:

In [78]:
def Euc_dist(r1,r2):
    dist = 0
    for i in range(len(r1)-1):
        dist = dist + ((r1[i]-r2[i])**2)
    return math.sqrt(dist)

Sort Function:

In [79]:
def sorting(distances):
    sorted_list = []
    copy_d = list() 
    copy_d = distances.copy()

    while distances:
        minimum = distances[0]
        for item in distances:
            if item < minimum:
                minimum = item
        sorted_list.append(minimum)
        distances.remove(minimum)
    return sorted_list

K Nearest Prediction:

In [80]:
def k_nearest_predict(sorted_list,copy_d,k,ytrain):
    l1,l2,l3=0,0,0
    for i in range(len(copy_d)):
        if sorted_list[0]==copy_d[i]:
            l1=i
        elif sorted_list[1]==copy_d[i]:
            l2=i
        elif sorted_list[2]==copy_d[i]:
            l3=i
    #print(l1,l2,l3)
    
    if k==1:
        ans1= ytrain[l1]
    elif k==3:
        if ytrain[l1]==ytrain[l2] or ytrain[l1]==ytrain[l3]:
            ans1= ytrain[l1]
        elif ytrain[l2]==ytrain[l3] or ytrain[l1]==ytrain[l2]:
            ans1= ytrain[l2]
        elif ytrain[l1]!=ytrain[l2]!=ytrain[l3]:
            ans1= ytrain[l1]
    return ans1

Similar Neighbours:

In [81]:
def similar_neighbours(train,test,k,ytrain):
    i=0
    j=0
    distances=list()
    answers=list()
    predict=list()
    sorted_list=list()
    copy_d=list()
    a=len(train)
    b=len(test)
    while j<b:
        while i < a:
            dist1=Euc_dist(train[i],test[j])
            distances.append(dist1)
            i=i+1
            #print(distances)
        copy_d=distances.copy()
        sorted_list=sorting(distances)
        predict=k_nearest_predict(sorted_list,copy_d,k,ytrain)
        answers.append(predict)
        i=0
        j=j+1
                
    #print(answers)
    return answers 

Calculating the Error Rate:

In [97]:
def error_rate(actual, predicted):
    cal_val = 0
    for i in range(len(actual)):
        if actual[i] == predicted[i]:
            cal_val += 1
    error=(1-(cal_val / float(len(actual))))*100
    accuracy=(cal_val / float(len(actual)))*100
    print('Error:',error,'\nAccuracy:',accuracy)
    return "--"

K=1 for Iris Dataset:

In [98]:
pred1=similar_neighbours(X1_train,X1_test,1,y1_train)
print(error_rate(y1_test,pred1))

Error: 10.526315789473683 
Accuracy: 89.47368421052632
--


K=3 for Iris Dataset:

In [99]:
pred2=similar_neighbours(X1_train,X1_test,3,y1_train)
print(error_rate(y1_test,pred2))

Error: 7.8947368421052655 
Accuracy: 92.10526315789474
--


K=1 for Ionosphere Dataset:

In [100]:
pred3=similar_neighbours(X2_train,X2_test,1,y2_train)
print(error_rate(y2_test,pred3))

Error: 22.72727272727273 
Accuracy: 77.27272727272727
--


K=3 for Ionosphere Dataset:

In [101]:
pred4=similar_neighbours(X2_train,X2_test,3,y2_train)
print(error_rate(y2_test,pred4))

Error: 22.72727272727273 
Accuracy: 77.27272727272727
--
